server:
  port: 8080

spring:
  application:
    name: ventas-bodega

  datasource:
    #url: jdbc:mysql://localhost:3306/ventasbodegadb
    url: jdbc:mysql://vps-5943657-x.dattaweb.com:3306/zavefy_db?allowPublicKeyRetrieval=true
    #url: jdbc:mysql://localhost:3306/zavefy_db?allowPublicKeyRetrieval=true
    #url: jdbc:mysql://vps-5943657-x.dattaweb.com:3306/zavefy_db?allowPublicKeyRetrieval=true
    #url: jdbc:mysql://localhost:3306/zavefy_db?allowPublicKeyRetrieval=true
    #username: root
    username: zavefy_user
    #password: 123456
    password: josesamuel
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 540000
      keepalive-time: 300000
      connection-timeout: 30000
      validation-timeout: 5000
  jpa:
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 25MB

security:
  jwt:
    key:
      private: mi_clave_super_secreta_123456
    user:
      generator: ventas-bodega-app

parameters:
  cookie_is_secure: false
  cookie_max_age: 1800
  cookie_name: auth_token
  cookie_http_only: true
  cookie_path: /

