server:
  port: 8080

spring:
  application:
    name: ventas-bodega

  datasource:
    #url: jdbc:mysql://localhost:3306/ventasbodegadb
    url: jdbc:mysql://vps-5943657-x.dattaweb.com:3306/zavefy_db?allowPublicKeyRetrieval=true
    #url: jdbc:mysql://localhost:3306/zavefy_db?allowPublicKeyRetrieval=true
    #username: root
    username: zavefy_user
    #password: 123456
    password: josesamuel
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update

security:
  jwt:
    key:
      private: mi_clave_super_secreta_123456
    user:
      generator: ventas-bodega-app